net install bim2ancestry, from(https://raw.github.com/ricanney/stata/master/functions/b) replace
net install bim2count, from(https://raw.github.com/ricanney/stata/master/functions/b) replace
net install bim2dta, from(https://raw.github.com/ricanney/stata/master/functions/b) replace
net install bim2eigenvec, from(https://raw.github.com/ricanney/stata/master/functions/b) replace
net install bim2frq, from(https://raw.github.com/ricanney/stata/master/functions/b) replace
net install bim2ldexclude, from(https://raw.github.com/ricanney/stata/master/functions/b) replace
net install bim2rymk, from(https://raw.github.com/ricanney/stata/master/functions/b) replace
net install bim_path_to_short, from(https://raw.github.com/ricanney/stata/master/functions/b) replace
net install checkfile, from(https://raw.github.com/ricanney/stata/master/functions/c) replace
net install checkloc_name, from(https://raw.github.com/ricanney/stata/master/functions/c) replace
net install checktabbed, from(https://raw.github.com/ricanney/stata/master/functions/c) replace
net install create_1000genomes, from(https://raw.github.com/ricanney/stata/master/functions/c) replace
net install create_generef, from(https://raw.github.com/ricanney/stata/master/functions/c) replace
net install create_hrc, from(https://raw.github.com/ricanney/stata/master/functions/c) replace
net install create_recombref, from(https://raw.github.com/ricanney/stata/master/functions/c) replace
net install dir2dta, from(https://raw.github.com/ricanney/stata/master/functions/d) replace
net install fam2dta, from(https://raw.github.com/ricanney/stata/master/functions/f) replace
net install files2dta, from(https://raw.github.com/ricanney/stata/master/functions/f) replace
net install gene_plotorder, from(https://raw.github.com/ricanney/stata/master/functions/g) replace
net install graphgene, from(https://raw.github.com/ricanney/stata/master/functions/g) replace
net install graphlocuszoom, from(https://raw.github.com/ricanney/stata/master/functions/g) replace
net install intersect_genes, from(https://raw.github.com/ricanney/stata/master/functions/i) replace
net install recodegenotype, from(https://raw.github.com/ricanney/stata/master/functions/r) replace
net install ref_path_to_short, from(https://raw.github.com/ricanney/stata/master/functions/r) replace
net install snp2build, from(https://raw.github.com/ricanney/stata/master/functions/s) replace
net install snp2refid, from(https://raw.github.com/ricanney/stata/master/functions/s) replace
net install summaryqc, from(https://raw.github.com/ricanney/stata/master/functions/s) replace
